### ISSUE TITLE
SMTP issues

### ISSUE THREAD

**Issue by dinger1986** [rustdesk/rustdesk-server-pro#26]
there have been afew reports of email issues, I have tried to setup gmail which requires "Access for less secure apps" enabled and also office 365, Gmail I at least get an error that makes sense office 365 just doesnt seem to connect (typical microsoft). It would be worth (if easy enough) to have options of SSL/TLS/None and also to not enforce usernames/passwords so direct send can be used https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#option-2-send-mail-directly-from-your-printer-or-application-to-microsoft-365-or-office-365-direct-send

**Comment by it-boerner** [comment]
Perhaps the problem with Office is that authentication must take place using an app password, since Office now requires 2FA?

**Comment by dinger1986** [comment]
Tried both with app passwords 👍

**Comment by it-boerner** [comment]
Kein Erfolg?

**Comment by todaysoftware** [comment]
I had this problem as it appeared to be due to IPv6, after disabling IPv6 I get a different error (see below). I am guessing but I suspect it is trying to connect directly to the port with TLS but you need to connect un-encrypted and use the STARTTLS command.

using openssl the following fails (i.e. trying to negotiate TLS straight away)
`openssl s_client -connect smtp.office365.com:587`
while the following succeeds (i.e. using STARTTLS)
`openssl s_client -connect smtp.office365.com:587 -starttls smtp`


![image](https://github.com/rustdesk/rustdesk-server-pro/assets/80295432/251d8ed8-8420-4756-a97c-efd7619999c2)
