### ISSUE TITLE
Customize the client and differentiate between security and network when disabling custom settings

### ISSUE THREAD

**Issue by 754628709** [rustdesk/rustdesk-server-pro#276]
When customizing the client, the Disable settings option distinguishes between network options and security options, because we don't want the customized client to see the key in the network, but we want to be able to set security settings, set passwords, etc. through the client. (We don't want to write a password when customizing the client, because that will result in a yellow prompt)
![1719306600278](https://github.com/rustdesk/rustdesk-server-pro/assets/84103483/7968057e-5636-483a-9b44-78ac1c144f2c)
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/84103483/891ed8c7-89c0-45e7-87b5-a616feb864a7)
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/84103483/39790043-1823-4c8e-b2ee-d1c0853a09a9)

**Comment by MPalatucciEng** [comment]
In addition to splitting the two settings, it would be really useful to allow users to be able to set only the proxy without seeing all the network settings. Because many companies to whom we give assistance are behind proxies, and it is a vulnerability to show the network settings, especially the key!

**Comment by rustdesk** [comment]
Ready now, https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#hide-security-settings--hide-network-settings--hide-server-settings--hide-proxy-settings
