### ISSUE TITLE
Allow addressbooks to be shared

### ISSUE THREAD

**Issue by dinger1986** [rustdesk/rustdesk-server-pro#49]
There should be an option to share addressbooks between users

**Comment by cblair334** [comment]
Absolutely.

**Comment by pdifeo** [comment]
The export/import of the address book could be useful. Is there a way to do this?

**Comment by pdifeo** [comment]
The export/import of the address book could be useful

Is there a way to do this?

**Comment by dennisrahmen** [comment]
Just bought the Personal license for testing but noticed that the address books are per user.
Would like to use this for a client which would need the Business license but without having the address book shared within the group it is not practical to switch from TeamViewer.

I would suggest the following:
- Keep the current system where every user has its own address book
- Add address books per group, so I can save a new entry either to my or the groups address book (if I have write permissions on that)

Bonus:
- Add address books as entry to the admin interface
- Make the address books I created there be editable there, so I can add host
- Automatically add host that are also in the group
- Make the address books be assignable to different groups

**Comment by rustdesk** [comment]
Maybe in 1.1.11 or 1.1.12.

**Comment by sesu-tech** [comment]
Agreed! It's a little tedious having to open up the web console, grab the ID for the end-user, then paste that into RustDesk to connect.

**Comment by MWicher** [comment]
We currently have version 1.1.13-1. Can you tell me when a central address book will be made available?

**Comment by sesu-tech** [comment]
I think it has been added in the latest version, 1.2.3. I see a new tab that lists all my users on the left and devices on the right:
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/25572885/9a2044cb-7eaf-49e3-954e-f81b4ebf2d40)

**Comment by MWicher** [comment]
we need a central, uniform company-wide address book.
Provided by the admin for the respective employees.
So far I only see the employees' address books.
Controlled in a similar way to Teamviewer.
Is something like that being planned?

**Comment by Elilitha** [comment]
Has this feature been added yet?

**Comment by 21pages** [comment]
@Elilitha Not yet, working on it

**Comment by 21pages** [comment]
In our client, we currently have a Group tab that displays all the users and devices accessible within the current team. We also have a personal address book that cannot be shared. I have implemented shared team address books that are accessible to the entire team, where each user can create, delete, modify, and view all address books. However, this doesn't seem reasonable, it still need some permission restrictions.

I have some rough ideas on permission restrictions:

1. No user or address book distinctions: The administrator decides whether non-admin users have the permissions to create, delete, and edit, while all users have view permissions.
2. User and address book distinctions: Only the administrator can create and delete address books, and they also determine which user groups have view or edit permissions for different address books.
3. User and address book distinctions: Instead of  team address books, each user has more than one personal address books. Users can share their address books with other user groups and decide which permissions they have.

Would like to hear more ideas.

**Comment by sesu-tech** [comment]
Personally, my only desire is to have an address book accessible to the whole team so the computers in the address book can be *named* and not just their ID, that's quicker for accessing employee's computers by their name. Then again, we're a small team.

I can see the value of more granular permissions and sharing with the address books that bigger or more complex teams would utilize, so I also support that. :)

**Comment by 21pages** [comment]
@sesu-tech , show the whole team is a critical desire.

**Comment by mycanaletto** [comment]
At the moment I don't know where to share my address book.

What I'd like is to be able (from my Rustdesk client connected to the pro server) to create one (or more) address books that I can share with other users.

These are customer addresses that we access in @public mode and that have a fixed password that I want to be able to save in the address book, modify the name and give it a label so that an employee can help the customer...

Sharing must be possible in RO or RW mode.

Ideally, with a right-click I should be able to say that such and such an address is shared in such and such a shared address book...

The groups we configure on the server are not usable because we're not going to configure occasional clients on the server. On the contrary, we leave them in public mode so that other people can use Rustedesk with the password that appears on the software.

That's how I use it ;-)

**Comment by 21pages** [comment]
@mycanaletto 
There will be multiple shared address books that allow IDs from public and self host servers . 
> that have a fixed password that I want to be able to save in the address book,

Regarding passwords, what about each address book has a option for sharing passwords? This way, users can group devices that require shared passwords in specific address books. The shared passwords should be manually set and not use remembered passwords when connecting, as this avoids sharing unwanted passwords and prevents temporary passwords from overriding fixed ones.

> Sharing must be possible in RO or RW mode.

Which of the three methods for restricting permissions mentioned above aligns better with your needs?

**Comment by rustdesk** [comment]
update: https://github.com/rustdesk/rustdesk/pull/7229

**Comment by BlockheadVFX-IT** [comment]
Any updates on this so far?

**Comment by rustdesk** [comment]
Update: https://github.com/rustdesk/rustdesk/pull/7229#issuecomment-1985529813

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.3.0
