### ISSUE TITLE
Custom OIDC is undebuggable

### ISSUE THREAD

**Issue by dasJ** [rustdesk/rustdesk-server-pro#66]
When trying to log in using custom OIDC, I get this message:
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/4971975/9ef69ee5-5365-4957-a5d5-fc380ce7a2c5)

This says pretty much nothing and doesn't help at all with debugging. `RUST_LOG=debug` adds no relevant information apart from reqwest (I assume) and h2 printing what they do.

I also find it weird that it's not possible to map the OIDC fields to RustDesk-internal ones. As there is no mapping, I have no idea at all what field it would use (I don't expect any field to have less than 4 characters).

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Remove lenght limit for oidc.

**Comment by Conni2461** [comment]
So spent the last hour debugging and we found the issue.

Our oidc issuer does not return, `name`/`username`/`preferred_username` in the `IdToken` but rather only returns these values for a UserInfo request.
We monitored the requests sent from rustdesk and noticed that a userinfo request was never sent.
So the length limit error is shown because the values are never present, resulting in a value smaller than 4.
I've looked this up in the core spec and realized that it is not required to have these claims present on IdTokens, so in my opinion you can't rely that these values are present and need to send an additional UserInfo request.

https://openid.net/specs/openid-connect-core-1_0.html#IDToken states what an ID Token must contains and it says to other Claims:

> ID Tokens MAY contain other Claims. Any Claims used that are not understood MUST be ignored. See Sections [3.1.3.6](https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken), [3.3.2.11](https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken), [5.1](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), and [7.4](https://openid.net/specs/openid-connect-core-1_0.html#SelfIssuedResponse) for additional Claims defined by this specification.

So it is not required to have the `name`/... claims in the IdToken response.

Furthermore it states in https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims that `profile` scope values are returned for the UserInfo Endpoint unless you use `response_type=id_token`. You guys use `response_type=code`, so you cant depend that these values are present and if they aren't you have to send an additional request.

> The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in [Section 5.3.2](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse), when a response_type value is used that results in an Access Token being issued. However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token.

If you guys use https://github.com/ramosbugs/openidconnect-rs you can just follow the gitlab exxample on how to send this additional request: https://github.com/ramosbugs/openidconnect-rs/blob/main/examples/gitlab.rs#L186

Hope this helps on finding a solution for this

**Comment by fufesou** [comment]
Thanks for your kindly help.

> If you guys use https://github.com/ramosbugs/openidconnect-rs

Yes, we use [openidconnect-rs](https://github.com/ramosbugs/openidconnect-rs), and we've already added the "profile" scope.

The "profile" scope is applyed in the step of Step 4, which you can't see.

![CKPIEU@LA144 %`CO6ODDZG](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/fb58b970-0c5f-4c06-b834-322398b2e487)

The "End User" can only see Step 2.

**Comment by fufesou** [comment]
We may try to use the email username or the "sub" field if no username can be fetched.

![CYYZ_IU7$B%Q6ZV}~79M7XC](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/eee00e33-62d5-43d9-82df-ef517cae2e36)

**Comment by Conni2461** [comment]
The problem is, step 4 doesnt happen. I know that a Enduser can't see that request but someone with access to the reverseproxy logs at least can see what routes are being it and we see the `authorize` and `token` request but i dont see any `userinfo` requests.

I tested this against the oidc issuer with the example provided by the library and it doesnt return a `name`, ..., etc in the `IdToken` Response. But its contained in the `UserInfo` response. With that example i btw see all 3 requests `authorize`, `token` as well as `userinfo` this is not the case when using rustdesk, so i have to assume that you currently dont send that `userinfo` request and only take the claims from the `IdToken` or that we somehow hit a edge case where the `userinfo` request isn't send

**Comment by fufesou** [comment]
The "The name is too short, at least 4 characters" message indicates that the [`exchange_code`](https://github.com/ramosbugs/openidconnect-rs/blob/414eb35419f84ab370c0d9acc3af72d72b67462c/examples/gitlab.rs#L161) is already called.

Which oidc provider did you use? Maybe it does not return the standard fields.

**Comment by Conni2461** [comment]
yeah exactly that what i am saying. You do the `exchange_code` request, and we see that request on reverse proxy level, but the `exchange_code` request doesn't actually return the `name` and `preferred_username`. It is not required by the the standard and our oidc doesnt do that. The `exchange_code` request returns the idtoken, but neither `name` nor `preferred_username` need to be present there. You guys are missing the userinfo request which actually returns all claims. you can't expect `name`, ... to be part of the `exchange_code` response as shown by your screenshot posted above and this part

> ID Tokens MAY contain other Claims. Any Claims used that are not understood MUST be ignored. See Sections [3.1.3.6](https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken), [3.3.2.11](https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken), [5.1](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), and [7.4](https://openid.net/specs/openid-connect-core-1_0.html#SelfIssuedResponse) for additional Claims defined by this specification.

https://github.com/ramosbugs/openidconnect-rs/blob/414eb35419f84ab370c0d9acc3af72d72b67462c/examples/gitlab.rs#L186-L187 is the request you are missing

**Comment by fufesou** [comment]
Thanks for pointing out the problem.

I just thought the standard claims will be returned by id token claims.

![1693834929303](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/6212d6f4-0b0b-436c-aab1-907958dea1e0)


Anyway, I'll try to read the standard claims from both the id token claims and the userinfo claims.

**Comment by Conni2461** [comment]
nice, that what i tried to explain to you that its only required that its part of the IdToken when `response_type=id_token` which isn't the case for rustdesk, see 5.4 as mentioned above.

Thanks for looking into it :D

**Comment by fufesou** [comment]
> The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in [Section 5.3.2](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse), when a response_type value is used that results in an Access Token being issued. However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token.

[Section 5.4](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)
I see this description, but to honest, I'm still confused.

> "when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token."

It seems to state that the "Claims" are in the "ID Token" if `response_type=id_token`.

But it does not matter, I've already read the "Claims" from both the "ID Token Claims" and the "UserInfo Claims".

Anyway, thank you again for your kind help.

**Comment by rustdesk** [comment]
1.1.10
